name: docker-build-push

on:
push:
branches:
- master

jobs:
build:
runs-on: ubuntu-latest

steps:
 - name: Checkout
    uses: actions/checkout@v4

 - name: Login Docker Hub
    uses: docker/login-action@v3
    with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

 - name: Build
    run: |
      docker build -t jeffersonalonco/to-do-list:v1 .

 - name: Push
    run: docker push jeffersonalonco/to-do-list:v1